CORE-5389: extending State Admin API with additional fields
manywho/sdk-dotnet pull request #23
Opened 2019-11-21 17:28 UTC by jacek-wojciechowski-dell

that were added recently to the model

2019-11-26 11:55 UTC, josecollazzi approved these changes

2019-11-26 12:34 UTC, jonjomckay requested changes

2019-11-26 12:34 UTC, jonjomckay commented on Run/Flow/FlowStackFrameAPI.cs
> +        [DataMember]
These new fields require documentation

2019-11-27 11:10 UTC, jonjomckay approved these changes

2019-12-11 10:49 UTC, merged